version: "3"
services:
  postgres:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    depends_on:
      - postgres