RemoveUnusedMethodsInModelsCheck: {
  except_methods: [
    'User#owned_device',
    'User#own_device',
    'User#fb_user_id',
    'User#fb_token',
    'User#as_indexed_json',
    'AuthIdentity#payload_value_for',
    'ContactMethod#main',
    'PinCode#unused_pin_code',
    'PinCode#random_dec',
    'PinCode#random_hex',
    'PinCode#random',
    'AuthIdentities::ClassicIdentity#by_email',
    'ApplicationRecord#resolvable_type',
    'PinCode#phone?',
    'PinCode#email?',
    'User#find_by_email',
    'User#liked_entities',
    'User#admin?',
    'User#blocked?',
    'Feedback#user_last_name',
    'Feedback#user_first_name',
    'Feedback#user_email'
  ]
}
